### ISSUE TITLE
Chrome 52 gives error "net::ERR_BLOCKED_BY_CLIENT", firefox works

### ISSUE THREAD

**Issue by cmdcolin** [klcodanr/Jekyll-Disqus-Forum#5]
I am seeing this error in stable chrome 52 when I try to open up a category in the forum e.g. general help

```
jquery-1.10.2.min.js:6 GET https://disqus.com/api/3.0/categories/listThreads.jsonp?callback=jQuery1102…FqMr4gm3HXXfERv7anOYHj3AZAyO2jD66Pqqe71B0&category=2736939&_=1470675605066 net::ERR_BLOCKED_BY_CLIENT
send    @   jquery-1.10.2.min.js:6
ajax    @   jquery-1.10.2.min.js:6
loadThreads @   category.js:11
(anonymous function)    @   category.js:63
```

Firefox appears to load the forum though

**Comment by cmdcolin** [comment]
Sorry this was due to having ghostery installed blocking disqus. It might be interesting if an error handler for thread loading failure was in place though

**Comment by eko24** [comment]
Be advised that same error could be thrown if your AdBlock is enabled.
